on: ["push", "pull_request"]
jobs:
  tsc2:
    uses: ./.github/workflows/npm-run-script.yml
    with:
      command: "tsc"
  standard:
    runs-on: "ubuntu-latest"
    steps:
      - id: npm-config
        run: "echo \"cache=$(npm config get cache)\" >> ${GITHUB_OUTPUT}"
      - uses: "actions/checkout@v4.2.2"
      - uses: "actions/cache@v4.2.0"
        with:
          path: ${{ steps.npm-config.outputs.cache }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: "npm run ci"
      - run: "npm run standard"
  test:
    runs-on: "ubuntu-latest"
    steps:
    - id: npm-config
      run: "echo \"cache=$(npm config get cache)\" >> ${GITHUB_OUTPUT}"
    - uses: "actions/checkout@v4.2.2"
    - uses: "actions/cache@v4.2.0"
      with:
        path: ${{ steps.npm-config.outputs.cache }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: "npm run ci"
    - run: "npm test"
