on: ["push", "pull_request"]
jobs:
  tsc:
    uses: ./.github/workflows/npm-run-script.yml
    with:
      command: "tsc"
  standard:
    uses: ./.github/workflows/npm-run-script.yml
    with:
      command: "standard"
  test:
    uses: ./.github/workflows/npm-run-script.yml
    with:
      command: "test"
