on:
  workflow_dispatch: {}
  release:
    types: [ published ]
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/npm-run-script.yml
    with:
      command: "publish"
